on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
    - main
    paths:
    - data/reference/**
    - src/**
  workflow_dispatch:
    branches: [ main ]


name: check taxon info

jobs:
  mapping:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get branch name
        run: |
          git branch --show-current
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install linux libraries
        run: |
          sudo apt install libsodium-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libgdal-dev libproj-dev
          sudo apt install libudunits2-dev
      - name: Install R packages
        run: |
          source("src/install_packages.R")
        shell: Rscript {0}

      - name: Retrieve and compare taxon keys
        run: |
          source("src/run_retrieve_compare_taxon_keys.R")
        shell: Rscript {0}
